# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from dfuse.bstream.v1 import bstream_pb2 as dfuse_dot_bstream_dot_v1_dot_bstream__pb2


class BlockStreamStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Blocks = channel.unary_stream(
        '/dfuse.bstream.v1.BlockStream/Blocks',
        request_serializer=dfuse_dot_bstream_dot_v1_dot_bstream__pb2.BlockRequest.SerializeToString,
        response_deserializer=dfuse_dot_bstream_dot_v1_dot_bstream__pb2.Block.FromString,
        )


class BlockStreamServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Blocks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BlockStreamServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Blocks': grpc.unary_stream_rpc_method_handler(
          servicer.Blocks,
          request_deserializer=dfuse_dot_bstream_dot_v1_dot_bstream__pb2.BlockRequest.FromString,
          response_serializer=dfuse_dot_bstream_dot_v1_dot_bstream__pb2.Block.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dfuse.bstream.v1.BlockStream', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BlockStreamV2Stub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Blocks = channel.unary_stream(
        '/dfuse.bstream.v1.BlockStreamV2/Blocks',
        request_serializer=dfuse_dot_bstream_dot_v1_dot_bstream__pb2.BlocksRequestV2.SerializeToString,
        response_deserializer=dfuse_dot_bstream_dot_v1_dot_bstream__pb2.BlockResponseV2.FromString,
        )


class BlockStreamV2Servicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Blocks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BlockStreamV2Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Blocks': grpc.unary_stream_rpc_method_handler(
          servicer.Blocks,
          request_deserializer=dfuse_dot_bstream_dot_v1_dot_bstream__pb2.BlocksRequestV2.FromString,
          response_serializer=dfuse_dot_bstream_dot_v1_dot_bstream__pb2.BlockResponseV2.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dfuse.bstream.v1.BlockStreamV2', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
